apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "issue-tracker.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "issue-tracker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
